openapi: 3.0.0
info:
  description: |
    NTCS administrator OpenAPIs.
  version: 1.0.0-oas3
  title: NTCS administrator - System Management/Code
  contact:
    email: contact@examples.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'www.examples.com/admin/v1'
tags:
  - name: 공통코드 관리
    description: 공통코드 관리
paths:
#
# 공통코드 관리
#
  /management/code:
    post:
      tags:
      - 공통코드
      summary: '공통코드 등록'
      operationId: addCommonCode
      parameters:
        - $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/parameters/xAuthToken'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonCodeRequestData'
      responses:
        '200':
          description: successful operation
        '400':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/400'
        '408':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/408'
    put:
      tags:
      - 공통코드  
      summary: '공통코드 수정'
      operationId: updateCommonCode
      parameters:
        - in: query
          name: langType
          description: '언어 (기본값: KOR)'
          required: true
          schema:
            type: string
            default: KOR

        - in: query
          name: commonGroupCd
          required: true
          schema:
            type: string

        - in: query
          name: commonCd
          required: true
          schema:
            type: string
          
        - $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/parameters/xAuthToken'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommonCodeRequestData'

      responses:
        '200':
          description: successful operation
        '400':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/400'
        '408':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/408'
    get:
      tags:
      - 공통코드 
      summary: '코드리스트 조회 (Simple)'
      description: 'Web Page 로딩 시, 공통코드 설정을 위해서 특정 코드그룹에 대한 코드 정보를 검색한다.'
      operationId: inquirySimpleCodeList
      parameters:
        - in: query
          name: langType
          description: '언어 (기본값: KOR)'
          required: true
          schema:
            type: string
            default: KOR
            
        - in: query
          name: commonGroupCd
          required: true
          schema:
            type: string
            
        - $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/parameters/xAuthToken'

      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
             schema:
              $ref: '#/components/schemas/CommonCodeSimpleList'          
        '400':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/400'
        '408':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/408'
  
  /management/code/list:
    get:
      tags:
        - 공통코드 
      summary: '코드그룹별 상세 코드 리스트 조회'
      description: '코드그룹에 대한 공통코드 상세정보 조회. 공통코드 전체 컬럼정보가 검색된다.'
      operationId: inquiryCommonCodeList
      parameters:
        - in: query
          name: langType
          description: '언어 (기본값: KOR)'
          required: true
          schema:
            type: string
            default: KOR
            
        - in: query
          name: commonGroupCd
          required: true
          schema:
            type: string
            
        - $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/parameters/xAuthToken'
      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
             schema:
              $ref: '#/components/schemas/CommonCodeResponseData'          
        '400':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/400'
        '408':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/408'

  /management/code/detail:
    get:
      tags:
        - 공통코드 
      summary: '특정 코드에 대한 상세정보 조회'
      description: '특정 코드에 대한  상세정보를 검색한다. 코드 전체 컬럼정보가 검색된다.'
      operationId: inquiryCommonCodeDetail
      parameters:
        - in: query
          name: langType
          description: '언어 (기본값: KOR)'
          required: true
          schema:
            type: string
            default: KOR           
        - in: query
          name: commonGroupCd
          required: true
          schema:
            type: string
        - in: query
          name: commonCd
          required: true
          schema:
            type: string            
            
        - $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/parameters/xAuthToken'

      responses:
        '200':
          description: successful operation
          content:
            application/problem+json:
             schema:
              $ref: '#/components/schemas/CommonCodeResponseData'          
        '400':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/400'
        '408':
          $ref: 'knc_common_data-1.0.0-oas3.yaml#/components/responses/408'   
components:
  schemas:
    TransactionId:
      type: string
      description: 'Unique string used to identify the request message. Used for message
        tracking purposes'
    TransactionTimeStamp:
      type: string
      description: Represents both a date and a time (yyyyMMddHHmmss.ns)
      example: '20210101000000.123'

#
# CommCodeList
#
    CommonCodeSimpleList:
      description: 단순 공통코드 마스터 데이터
      type: array
      items:
        $ref: 'ntcs_reference_data-1.0.0-oas3.yaml#/components/schemas/TsyCodeList'
#
# CommonCode
#
    CommonCodeData:
      description: 공통코드 마스터 데이터
      type: object
      properties:
        transId:
          $ref: '#/components/schemas/TransactionId'
        transTimeStamp:
          $ref: '#/components/schemas/TransactionTimeStamp'
        messageBody:
          type: object
          properties:
            recordsTotal:
              description: 최대 레코드 건수
              type: integer
              format: int32
              minimum: 0
            recordsFiltered:
              description: 필터링된 레코드 건수.
              type: integer
              format: int32
              minimum: 0          
            data:
              type: array
              items: 
                $ref: 'ntcs_reference_data-1.0.0-oas3.yaml#/components/schemas/TsyCodeDetail'
    
    CommonCodeRequestData:
      $ref: '#/components/schemas/CommonCodeData'
    CommonCodeResponseData:
      $ref: '#/components/schemas/CommonCodeData'